export const tutorData = [
  {
    id: "intro",
    title: "1. Hard vs Soft Computing",
    easyConcept: "Think of Hard Computing as traditional programming: precise, exact, and rigid. Soft Computing is how humans think: it deals with uncertainty, partial truths, and approximations to solve real-world problems gracefully.",
    visualGuide: "Visualize a traditional computer computing exactly '2.00000000 + 2.00000000 = 4.00000000' (Hard Computing). Then visualize a human looking at a car and saying 'It's moving pretty fast' (Soft Computing).",
    hasVisualizer: "none",
    examQuestions: [
      { q: "Write down the difference between hard computing and soft computing. / Explain the between hard and soft computing.", a: "**Exam Ready Answer:**\n**Hard Computing:**\n1. Based on precision, certainty, and rigorous mathematical models.\n2. Requires exact input data; produces exact output.\n3. Intolerant to imprecision and uncertainty.\n4. Uses two-valued logic (0 and 1).\n\n**Soft Computing:**\n1. Based on approximation, uncertainty, and partial truth.\n2. Can handle noisy, incomplete, or ambiguous input data.\n3. Highly tolerant to imprecision and uncertainty.\n4. Uses multi-valued logic (Fuzzy logic) and probabilistic reasoning." },
      { q: "What is soft computing? What are the components of soft computing?", a: "**Exam Ready Answer:**\n**Definition:** Soft computing is an umbrella term for computational techniques that attempt to study, model, and analyze highly complex phenomena, exploiting tolerance for imprecision to achieve robustness and low-cost solutions.\n**Components:**\n1. Fuzzy Logic (FL)\n2. Artificial Neural Networks (ANN)\n3. Evolutionary Computation / Genetic Algorithms (GA)\n4. Machine Learning (ML)\n5. Probabilistic Reasoning (PR)" },
      { q: "Mention different categories of soft computing techniques and give one example for each.", a: "**Exam Ready Answer:**\n1. **Fuzzy Logic:** Example: Washing machine wash time controller based on 'dirtiness'.\n2. **Neural Networks:** Example: Handwritten character recognition.\n3. **Genetic Algorithms:** Example: Solving the Travelling Salesman Problem.\n4. **Swarm Intelligence:** Example: Ant Colony Optimization for network routing." },
      { q: "Core of soft Computing is...", a: "**Answer:** Fuzzy Logic, Neural Networks, and Genetic Algorithms." },
      { q: "(IV) Hard computing produces precise results - True/False?", a: "**Answer:** True." },
      { q: "(VII) Soft computing is used to solve non-linear issues - True/False?", a: "**Answer:** True. Soft computing techniques map complex non-linear relationships." },
      { q: "Automated vehicle is an example of ______.", a: "**Answer:** Control system utilizing Soft Computing." }
    ],
    quiz: [
      { type: "mcq", q: "Which of the following is NOT a primary component of Soft Computing?", options: ["Fuzzy Logic", "Genetic Algorithms", "Rigid Boolean Logic", "Neural Networks"], answer: 2, explanation: "Rigid Boolean Logic belongs to Hard Computing." },
      { type: "mcq", q: "Which type of computing requires an exact mathematical model?", options: ["Hard Computing", "Soft Computing", "Both", "Neither"], answer: 0, explanation: "Hard computing requires exact mathematical models." },
      { type: "mcq", q: "Soft computing is primarily used to solve linear problems. True or False?", options: ["True", "False"], answer: 1, explanation: "False. Soft computing excels at solving complex, non-linear problems." },
      { type: "long", q: "Explain the fundamental difference between Hard Computing and Soft Computing regarding their tolerance for imprecision." },
      { type: "long", q: "List three main components of Soft Computing and provide a real-world application for one of them." },
      { type: "mcq", q: "Which computing paradigm is inspired by the human mind's ability to reason with uncertainty?", options: ["Hard Computing", "Quantum Computing", "Soft Computing", "Cloud Computing"], answer: 2, explanation: "Soft Computing is modeled after human reasoning, which gracefully handles uncertainty." },
      { type: "long", q: "Why is an automated vehicle considered an application of Soft Computing rather than purely Hard Computing?" },
      { type: "mcq", q: "Hard computing is tolerant of noisy or incomplete data.", options: ["True", "False"], answer: 1, explanation: "False. Hard computing requires exact, complete inputs." },
      { type: "long", q: "Describe a scenario where Hard Computing would fail, but Soft Computing would succeed." },
      { type: "mcq", q: "Which logic does Hard Computing primarily use?", options: ["Fuzzy Logic", "Multi-valued Logic", "Two-valued Boolean Logic", "Probabilistic Logic"], answer: 2, explanation: "Hard computing relies on strict 0s and 1s (True/False)." },
      { type: "long", q: "Discuss the role of Probabilistic Reasoning within the Soft Computing framework." },
      { type: "mcq", q: "Soft computing aims to achieve:", options: ["Absolute precision", "Tractability, robustness, and low-cost solutions", "Mathematical proofs", "Binary outputs"], answer: 1, explanation: "By tolerating imprecision, it achieves tractability, robustness, and low cost." }
    ]
  },
  {
    id: "fuzzy_basics",
    title: "2. Fuzzy Sets & Basics",
    easyConcept: "Fuzzy logic allows partial truth (values between 0 and 1). Instead of just 'Hot' or 'Cold', a room can be '0.7 Hot'. Crisp sets are black and white; fuzzy sets are shades of gray.",
    visualGuide: "Interactive Tool Below! Adjust the Alpha (α) threshold to see how the fuzzy triangle gets 'cut' to form a crisp interval.",
    hasVisualizer: "fuzzy",
    examQuestions: [
      { q: "What are the differences between crisp set and fuzzy set? / Differentiate between Fuzzy logic and Classical Logic.", a: "**Exam Ready Answer:**\n**Crisp Set / Classical Logic:**\n1. Membership is strict: {0, 1}.\n2. Sharp and unambiguous boundaries.\n3. Law of Excluded Middle holds true (A or Not A).\n4. Law of Contradiction holds true (Cannot be A and Not A).\n\n**Fuzzy Set / Fuzzy Logic:**\n1. Membership is continuous from [0, 1].\n2. Gradual and ambiguous boundaries.\n3. Law of Excluded Middle does NOT hold true.\n4. Law of Contradiction does NOT hold true." },
      { q: "Law of contradiction and law of excluded middle cannot be applied to fuzzy sets. Give proper justification to the statement.", a: "**Exam Ready Answer:**\nIn classical sets, the Law of Excluded Middle states $A \\cup A' = X$, and the Law of Contradiction states $A \\cap A' = \\emptyset$.\n\n**Justification for Fuzzy Sets:**\nLet an element $x$ have a membership value $\\mu_A(x) = 0.5$ in a fuzzy set A.\nIts complement membership $\\mu_{A'}(x) = 1 - 0.5 = 0.5$.\n\nFor Excluded Middle: $\\mu_{A \\cup A'}(x) = \\max(0.5, 0.5) = 0.5 \\neq 1$. Thus, $A \\cup A' \\neq X$.\nFor Contradiction: $\\mu_{A \\cap A'}(x) = \\min(0.5, 0.5) = 0.5 \\neq 0$. Thus, $A \\cap A' \\neq \\emptyset$." },
      { q: "What do you mean by fuzzification?", a: "**Exam Ready Answer:**\nFuzzification is the process of converting a crisp (exact) input value into a fuzzy linguistic variable using membership functions. Example: A temperature sensor reads a crisp value of $28^\\circ C$. Fuzzification maps this to linguistic variables like $0.8$ Warm and $0.2$ Hot." },
      { q: "Differentiate between Normal and subnormal fuzzy set. Using Intuition, plot fuzzy membership functions to: Liquid level in the tank.", a: "**Exam Ready Answer:**\n- **Normal Fuzzy Set:** A fuzzy set where the maximum membership value (height) is exactly equal to 1.\n- **Subnormal Fuzzy Set:** A fuzzy set where the maximum membership value is strictly less than 1.\n\n**Plotting Instruction:**\n- X-axis: Liquid Level (0 to 100L).\n- Y-axis: Membership Degree $\\mu$ (0 to 1).\n- Draw three triangles: **Empty** (peak at 0), **Half-Full** (peak at 50), **Full** (peak at 100)." },
      { q: "Write short notes on: Fuzzy Membership Functions", a: "**Exam Ready Answer:**\nA membership function (MF) is a curve that defines how each point in the input space is mapped to a membership value between 0 and 1. Common shapes include Triangular, Trapezoidal, and Gaussian MFs." },
      { q: "Explain convex fuzzy set and non-convex fuzzy set.", a: "**Exam Ready Answer:**\n- **Convex Fuzzy Set:** The membership function only has one peak. It goes up, reaches a maximum, and comes down. Mathematically: $\\mu_A(\\lambda x_1 + (1-\\lambda)x_2) \\ge \\min(\\mu_A(x_1), \\mu_A(x_2))$.\n- **Non-Convex Fuzzy Set:** The membership function has multiple local peaks." },
      { q: "What do you mean by height of a Fuzzy set?", a: "**Exam Ready Answer:**\nThe height of a fuzzy set is the supremum (maximum) of all the membership grades in that set. If height = 1, it's 'Normal'. If < 1, it's 'Subnormal'." },
      { q: "Which theory defines the GA most? / Fuzzy set theory was introduced by / The boundary of the fuzzy set A is defined by...", a: "**Quick Answers:**\n- GA is defined by **Darwin's Theory of Evolution**.\n- Fuzzy set theory was introduced by **Lotfi A. Zadeh**.\n- Boundary of fuzzy set: Elements where $0 < \\mu_A(x) < 1$." },
      { q: "How many types of random variables are there in fuzzy logic?", a: "**Answer:** Fuzzy logic uses linguistic variables rather than traditional statistical random variables." },
      { q: "In membership function graph, X axis represents which parameter?", a: "**Answer:** The Universe of Discourse (the actual exact values, like temperature in degrees)." },
      { q: "Let F = 0.5/a + 0.5/b be a fuzzy set. Find fuzzy cardinality of F.", a: "**Answer:** The scalar cardinality is the sum of membership values: $0.5 + 0.5 = 1.0$." },
      { q: "A fuzzy number B is a fuzzy set in the real line (R) that satisfies the condition(s)", a: "**Answer:** It must be normal and convex." },
      { q: "Which of the following can be regarded as a fuzzy linguistic truth value?", a: "**Answer:** Terms like 'Very True', 'Fairly False', etc." },
      { q: "Which one follow the involution property of fuzzy complement?", a: "**Answer:** Standard Zadeh's complement: $1 - (1 - A) = A$." }
    ],
    quiz: [
      { type: "mcq", q: "If the highest membership value in a fuzzy set is 0.8, the set is:", options: ["Normal", "Convex", "Subnormal", "Crisp"], answer: 2, explanation: "A fuzzy set is subnormal if its maximum membership value is less than 1.0." },
      { type: "mcq", q: "Which classical logic law fails in Fuzzy Logic?", options: ["De Morgan's Law", "Associative Law", "Law of Excluded Middle", "Commutative Law"], answer: 2, explanation: "The Law of Excluded Middle and Law of Contradiction do not hold in fuzzy logic." },
      { type: "long", q: "Explain why the Law of Excluded Middle (A ∪ A' = Universe) does not hold true in Fuzzy Logic." },
      { type: "mcq", q: "Fuzzy set theory was introduced by:", options: ["McCulloch", "Pitts", "Lotfi A. Zadeh", "Alan Turing"], answer: 2, explanation: "Lotfi A. Zadeh introduced fuzzy sets in 1965." },
      { type: "long", q: "Define what a 'Normal' fuzzy set is and provide an example of its height." },
      { type: "mcq", q: "The boundary of a fuzzy set consists of elements where the membership value is:", options: ["Exactly 0", "Exactly 1", "Between 0 and 1 exclusive", "Less than 0"], answer: 2, explanation: "Boundary elements have partial membership (0 < mu < 1)." },
      { type: "long", q: "Describe the difference between a convex and non-convex fuzzy set visually and mathematically." },
      { type: "mcq", q: "What does the X-axis represent in a membership function graph?", options: ["Membership degree", "Universe of Discourse", "Alpha-cut threshold", "Centroid"], answer: 1, explanation: "The X-axis holds the actual crisp values (Universe of Discourse)." },
      { type: "long", q: "Explain the process of 'fuzzification' with a real-world example." },
      { type: "mcq", q: "A fuzzy number must satisfy which two conditions?", options: ["Normal and Convex", "Subnormal and Concave", "Crisp and Continuous", "Discrete and Normal"], answer: 0, explanation: "By definition, a fuzzy number must be normal and convex." },
      { type: "long", q: "Justify why the Law of Contradiction fails when applied to a fuzzy set with membership value 0.5." },
      { type: "mcq", q: "What is the scalar cardinality of a fuzzy set F = {0.2/a, 0.4/b, 0.7/c}?", options: ["0.7", "1.3", "3.0", "1.0"], answer: 1, explanation: "Scalar cardinality is the sum: 0.2 + 0.4 + 0.7 = 1.3." }
    ]
  },
  {
    id: "fuzzy_math",
    title: "3. Fuzzy Math, Operations & Alpha Cuts",
    easyConcept: "Math with fuzzy sets: Union (OR) is MAXIMUM. Intersection (AND) is MINIMUM. Complement (NOT) is 1 minus the value. An Alpha-Cut slices the fuzzy set horizontally at a threshold α to extract a crisp set of all elements above that threshold.",
    visualGuide: "Interactive Tool Below! See how Union traces the highest points (max) and Intersection traces the lowest points (min) of two overlapping fuzzy sets.",
    hasVisualizer: "fuzzy_ops",
    examQuestions: [
      { q: "Mathematical Problem: Calculate Drastic Sum, Algebraic Sum, and Bounded Product for two fuzzy values.", a: "**Step-by-Step Math Guide:**\nLet $a = 0.6$ and $b = 0.8$.\n**1. Algebraic Sum:** $a + b - (a \\times b) = 0.6 + 0.8 - 0.48 = \\textbf{0.92}$\n**2. Bounded Sum (Product):** $\\max(0, a + b - 1) = \\max(0, 0.4) = \\textbf{0.4}$\n**3. Drastic Sum:** Equals $a$ if $b=0$, $b$ if $a=0$, else $1$. Since $a, b \\neq 0$, Drastic Sum = $\\textbf{1.0}$." },
      { q: "Let X = {1, 2, 3, 4} and Y = {a, b, c, d}. Calculate A U B', B' - A, R = C x B.", a: "**Formulas:**\n- **Complement (B'):** $\\mu_{B'}(x) = 1 - \\mu_B(x)$\n- **Union (A U B'):** $\\max(\\mu_A(x), \\mu_{B'}(x))$\n- **Difference (B' - A):** Equivalent to $B' \\cap A'$. So, $\\min(\\mu_{B'}(x), 1 - \\mu_A(x))$.\n- **Cartesian Product (C x B):** Forms a matrix where relation $R(c,b) = \\min(\\mu_C(c), \\mu_B(b))$." },
      { q: "Define alpha-cut and strong alpha-cut with example. / Describe Lambda cut of a fuzzy set.", a: "**Exam Ready Answer:**\n- **Alpha-cut ($\\alpha$-cut):** A CRISP set containing elements whose membership grade is $\\ge \\alpha$. ($A_\\alpha = \\{ x \\in X | \\mu_A(x) \\ge \\alpha \\}$)\n- **Strong Alpha-cut:** A crisp set containing elements whose membership grade is strictly $> \\alpha$.\n**Example:** Let $A = \\{0.2/x_1, 0.5/x_2, 0.8/x_3, 1.0/x_4\\}$. \nIf $\\alpha = 0.5$, then $\\alpha$-cut $A_{0.5} = \\{x_2, x_3, x_4\\}$. The strong 0.5-cut $A_{0.5+} = \\{x_3, x_4\\}$." },
      { q: "Prove that for any set A, A - B = A ∩ B' using Fuzzy Set operations.", a: "**Mathematical Proof:**\nThe difference $A - B$ means 'elements in A that are NOT in B'.\nIn fuzzy logic, this is calculated by taking the intersection of A and the complement of B.\nTherefore: $\\mu_{A - B}(x) = \\min( \\mu_A(x), 1 - \\mu_B(x) )$.\nLet $\\mu_A(x) = 0.7$, $\\mu_B(x) = 0.4$. $\\mu_{B'}(x) = 0.6$. $\\mu_{A - B}(x) = \\min(0.7, 0.6) = \\textbf{0.6}$." },
      { q: "What do you mean by decomposition of a fuzzy set? Prove that for any A in F(X), A = U (α * A_α).", a: "**Exam Ready Answer:**\n**Decomposition Theorem:** Any fuzzy set can be decomposed into a series of crisp $\\alpha$-cuts, and reconstructed from them.\n**Proof Sketch:** For element x, let membership be $m$. For any $\\alpha \\le m$, x is in $A_\\alpha$, so $\\alpha \\times A_\\alpha(x) = \\alpha$. For $\\alpha > m$, x is not in $A_\\alpha$, so $\\alpha \\times A_\\alpha(x) = 0$. Taking the union (max) over all $\\alpha$ gives $\\max(\\alpha)$ where $\\alpha \\le m$, which is exactly $m$." },
      { q: "Find the Fuzzy Hamming distance and Euclidean distance between given two fuzzy set.", a: "**Exam Ready Answer:**\n1. **Hamming Distance:** Sum of absolute differences. $d_H(A, B) = \\sum | \\mu_A(x) - \\mu_B(x) |$\n2. **Euclidean Distance:** Square root of the sum of squared differences. $d_E(A, B) = \\sqrt{ \\sum (\\mu_A(x) - \\mu_B(x))^2 }$" },
      { q: "Whether a power set can be formed for a fuzzy set. Justify your answer.", a: "**Answer:** Yes, a fuzzy power set can be formed. It contains all possible fuzzy subsets of the given fuzzy set." },
      { q: "Let F = 0/0 + 1/1 be a fuzzy set on the universe U = {0, 1}. Which of the following is L (F), i.e., the level set of F?", a: "**Answer:** The level set contains the distinct membership values, which are {0, 1}." },
      { q: "Let be F= 0.6/a + 0.2/b + 0.3/c + 0.9/d a fuzzy set. Find a set of alpha-cuts such that F= Ualpha.Falpha. How many such sets of alpha-cuts are there?", a: "**Answer:** The alpha values are the unique membership degrees: {0.2, 0.3, 0.6, 0.9}. So there are 4 sets of alpha-cuts required to decompose F." },
      { q: "Which of the following is true regarding variation of the size C of a fuzzy set a increases from 0 to 1 ?", a: "**Answer:** As alpha (the slice level) increases, the size (cardinality) of the resulting crisp alpha-cut set decreases." },
      { q: "The elements in two sets A and B are given as A = {2, 4} and B = {a, b, c}. Find the various Cartesian product of these two sets.", a: "**Answer:** A x B = {(2,a), (2,b), (2,c), (4,a), (4,b), (4,c)}." }
    ],
    quiz: [
      { type: "mcq", q: "If A(x) = 0.6 and B(x) = 0.8, what is the value of Union (A U B) using standard max operator?", options: ["0.6", "0.8", "1.4", "0.48"], answer: 1, explanation: "Fuzzy union is max(0.6, 0.8) = 0.8." },
      { type: "mcq", q: "An alpha-cut at α=0.5 will return a fuzzy set. True or False?", options: ["True", "False"], answer: 1, explanation: "False! An alpha-cut ALWAYS generates a CRISP set." },
      { type: "long", q: "Define what an Alpha-Cut is and describe how it converts a fuzzy set into a crisp set." },
      { type: "mcq", q: "What is the formula for calculating the Hamming distance between two fuzzy sets?", options: ["Square root of squared differences", "Sum of absolute differences", "Max of differences", "Min of differences"], answer: 1, explanation: "Hamming distance is the sum of the absolute differences of their membership values." },
      { type: "long", q: "Explain the Decomposition Theorem of fuzzy sets. How do alpha-cuts help reconstruct the original fuzzy set?" },
      { type: "mcq", q: "If the membership value a=0.7 and b=0.4, what is the Bounded Sum (Lukasiewicz T-norm)?", options: ["0.1", "1.1", "0.28", "1.0"], answer: 0, explanation: "max(0, a + b - 1) = max(0, 0.7 + 0.4 - 1) = max(0, 0.1) = 0.1" },
      { type: "long", q: "Calculate the Euclidean distance between A={0.5/x, 0.2/y} and B={0.1/x, 0.5/y}. Show the formula." },
      { type: "mcq", q: "What does the Cartesian product of two fuzzy sets create?", options: ["A crisp set", "A single fuzzy value", "A fuzzy relation matrix", "An alpha-cut"], answer: 2, explanation: "A Cartesian product generates a fuzzy relation matrix using the MIN operator across elements." },
      { type: "long", q: "Prove mathematically that A - B is equivalent to A ∩ B' in fuzzy logic." },
      { type: "mcq", q: "As the alpha-cut threshold increases from 0 to 1, the number of elements in the resulting crisp set:", options: ["Increases", "Decreases", "Stays the same", "Becomes negative"], answer: 1, explanation: "As the bar gets higher, fewer elements meet the threshold, shrinking the set." },
      { type: "long", q: "Calculate the Algebraic Sum of two fuzzy elements A=0.3 and B=0.9. Show your calculation step-by-step." },
      { type: "mcq", q: "The Drastic Sum of a=0.4 and b=0.5 evaluates to:", options: ["0.9", "1.0", "0.4", "0.5"], answer: 1, explanation: "Drastic sum rule: equals 1.0 since neither a nor b is zero." }
    ]
  },
  {
    id: "fuzzy_inference",
    title: "4. Fuzzy Inference Systems (FIS) & Defuzzification",
    easyConcept: "FIS uses 4 steps: 1) Fuzzify inputs, 2) Check IF-THEN Rule Base, 3) Inference (apply rules via Max-Min), 4) Defuzzify (convert the blurry output to an exact number using Centroid or Mean of Maxima).",
    visualGuide: "Max-Min composition: Matrix multiplication where * is replaced by MIN, and + is replaced by MAX. Defuzzification finds the center of gravity (Centroid) of the output shape.",
    hasVisualizer: "none",
    examQuestions: [
      { q: "Explain the structure of fuzzy inference system with an example. / Explain Mamdani fuzzy system.", a: "**Exam Ready Answer:**\n**Structure of FIS:**\n1. **Fuzzifier:** Transforms crisp inputs (e.g., Temp = $32^\\circ$) into fuzzy sets ('Hot' = 0.8).\n2. **Rule Base:** Contains linguistic IF-THEN rules (e.g., IF Temp is Hot THEN Fan is Fast).\n3. **Inference Engine:** Applies rules. Mamdani uses `min` for AND, `max` for OR, and clips output shapes.\n4. **Defuzzifier:** Converts aggregated fuzzy output back into a single crisp number.\n**Mamdani FIS:** Both inputs and outputs are fuzzy sets. It evaluates all rules, aggregates the output fuzzy sets, and uses Centroid for defuzzification." },
      { q: "Compare Sugeno FIS and Mamdani FIS?", a: "**Exam Ready Answer:**\n**Mamdani FIS:**\n- **Output:** Fuzzy set.\n- **Defuzzification:** Calculates centroid of complex shapes (computationally heavy).\n- **Usage:** Intuitive, captures human expert knowledge well.\n\n**Sugeno FIS (Takagi-Sugeno):**\n- **Output:** Mathematical function (crisp equation), e.g., $z = ax + by + c$.\n- **Defuzzification:** Simple weighted average (computationally fast).\n- **Usage:** Better for mathematical analysis and control systems." },
      { q: "Discuss defuzzification methods: Center of Sum (CoM), Mean of Maxima (MoM), Centroid.", a: "**Exam Ready Answer:**\n1. **Centroid (Center of Gravity):** Finds the balance point of the fuzzy shape. Formula: $Z^* = \\frac{\\sum (\\mu(x_i) \\times x_i)}{\\sum \\mu(x_i)}$. Most accurate.\n2. **Mean of Maxima (MoM):** Identifies the highest plateau (maximum membership). Calculates the average of the domain values (x-axis) reaching this maximum. Fast, but ignores the rest of the shape.\n3. **Center of Sums (CoS):** Calculates the algebraic sum of areas of individual fuzzy output sets, finding the center. Overlapping areas are counted twice." },
      { q: "Mathematical Problem: Perform max-min composition (RoS) for Fuzzy Relations R, S.", a: "**Step-by-Step Math Guide:**\nGiven $R_{m \\times n}$ and $S_{n \\times p}$. To find element $T_{ij}$:\n1. Look at row $i$ of R, column $j$ of S.\n2. Pair corresponding elements.\n3. Take the **minimum** of each pair.\n4. Take the **maximum** of all those minimums.\nFormula: $T_{ij} = \\max_k [ \\min( R_{ik}, S_{kj} ) ]$." },
      { q: "Explain how fuzzy logic is applied in home appliances?", a: "**Exam Ready Answer:**\nExample: Washing Machine. Sensors measure crisp inputs: 'Dirtiness' and 'Grease'. The FIS fuzzifies these into values like 'High Dirt' and 'Medium Grease'. The Rule Base evaluates rules like: 'IF Dirt is High AND Grease is Medium THEN Wash Time is Long'. The inference engine calculates a fuzzy wash time, and defuzzification converts it to a crisp output, setting the timer to exactly 42 minutes." },
      { q: "What is the main intention of the defuzzyfication height method?", a: "**Answer:** To quickly find a single crisp value by taking the peak (highest) membership value." },
      { q: "What is fuzzy rule base?", a: "**Answer:** A knowledge repository consisting of a set of linguistic 'IF-THEN' rules that map the fuzzy input space to the fuzzy output space based on expert knowledge." },
      { q: "For a speed control of DC motor, the membership function of series resistance, armature current and speed are given. Obtain Relation T using max-min composition.", a: "**Answer:** This requires setting up the fuzzy matrices for resistance/current and current/speed, and applying the Max-Min matrix composition $T_{ij} = \\max [ \\min( R_{ik}, S_{kj} ) ]$." }
    ],
    quiz: [
      { type: "mcq", q: "Which FIS method produces a mathematical equation directly as the output of a rule?", options: ["Mamdani", "Sugeno", "Zadeh", "Tsukamoto"], answer: 1, explanation: "Sugeno outputs crisp mathematical equations." },
      { type: "mcq", q: "In Max-Min composition, matrix multiplication is modified by replacing multiplication with ___ and addition with ___.", options: ["Max, Min", "Min, Max", "Sum, Product", "Product, Sum"], answer: 1, explanation: "MIN replaces multiplication, MAX replaces addition." },
      { type: "long", q: "Discuss the structural differences between Mamdani FIS and Sugeno FIS." },
      { type: "mcq", q: "Which defuzzification method finds the exact center of gravity of the output shape?", options: ["Mean of Maxima", "Center of Sums", "Centroid", "Height Method"], answer: 2, explanation: "Centroid calculates the balance point." },
      { type: "long", q: "Explain the four primary stages of a Fuzzy Inference System (FIS)." },
      { type: "mcq", q: "The Rule Base in an FIS is composed of what?", options: ["Matrix equations", "IF-THEN linguistic rules", "Neural network weights", "Binary trees"], answer: 1, explanation: "It relies on IF-THEN rules provided by human experts." },
      { type: "long", q: "In a Max-Min composition, if Row 1 of R is [0.4, 0.7] and Col 1 of S is [0.9, 0.2], calculate the resulting matrix element T(1,1)." },
      { type: "mcq", q: "Which of the following makes the Mean of Maxima (MoM) defuzzification method faster but less accurate than Centroid?", options: ["It integrates the entire curve", "It only looks at the highest peak(s) of the membership function", "It uses Sugeno equations", "It skips the fuzzification step"], answer: 1, explanation: "MoM ignores the overall shape and only averages the points at the maximum height." },
      { type: "long", q: "Provide a real-world example of how a fuzzy rule base might control an air conditioner." },
      { type: "mcq", q: "Defuzzification is the process of converting:", options: ["Crisp to Fuzzy", "Fuzzy to Crisp", "Rules to Matrices", "Weights to Inputs"], answer: 1, explanation: "It takes the blurry fuzzy output and yields a single exact number." },
      { type: "long", q: "Compare Center of Sums (CoS) and Centroid defuzzification methods regarding how they treat overlapping fuzzy areas." },
      { type: "mcq", q: "The main intention of the defuzzification height method is to:", options: ["Find the center of gravity", "Take the average of the maxima", "Take the peak highest membership value directly", "Integrate the curve"], answer: 2, explanation: "Height method is a very fast approach that just takes the peak value." }
    ]
  },
  {
    id: "neural_basics",
    title: "5. Artificial Neural Networks (ANN) - Basics",
    easyConcept: "ANN mimics the human brain. Neurons (nodes) are connected by synapses (weights). Each neuron multiplies inputs by weights, adds them up, and passes the sum through an 'Activation Function' to decide if it fires.",
    visualGuide: "Interactive Tool Below! Input values for X1, X2, W1, W2, and Bias. See how the Summation block computes Net Input, and how the Activation Threshold determines Output.",
    hasVisualizer: "neuron",
    examQuestions: [
      { q: "Map biological neuron to McCulloch-Pitts mathematical neuron.", a: "**Exam Ready Answer:**\n1. **Dendrites (Receptors):** Inputs ($X_1, X_2, ..., X_n$).\n2. **Synapses (Connection Strength):** Weights ($W_1, W_2, ..., W_n$).\n3. **Soma (Cell Body):** Summation Function ($\\sum W_i X_i + b$) which calculates net input.\n4. **Threshold / Action Potential:** Activation Function ($f$), determining if neuron fires.\n5. **Axon (Transmitter):** Output ($Y$)." },
      { q: "What is the necessity of activation function ? List the commonly used activation functions.", a: "**Exam Ready Answer:**\n**Necessity:** Introduces **non-linearity**. Without it, a deep network collapses into a single linear equation, unable to map complex real-world data.\n**Common Functions:**\n1. **Step / Binary:** Outputs 0 or 1 based on threshold.\n2. **Sigmoid / Logistic:** Outputs between 0 and 1, used in Backpropagation.\n3. **Tanh:** Outputs between -1 and 1.\n4. **ReLU:** $f(x) = \\max(0, x)$. Popular in deep learning." },
      { q: "Significance of weights & bias values in ANN.", a: "**Exam Ready Answer:**\n- **Weights (w):** Represent the strength of a connection. Learning involves adjusting weights to minimize error.\n- **Bias (b):** An offset to the net input. It shifts the activation function curve left or right, allowing better data fitting (like the y-intercept 'c' in $y = mx + c$)." },
      { q: "Discuss various ANN architectures in details.", a: "**Exam Ready Answer:**\n1. **Single-Layer Feedforward:** Inputs connect directly to outputs. (Perceptron). Can only solve linearly separable problems.\n2. **Multi-Layer Feedforward (MLP):** Contains hidden layers. Signals flow forward. Solves non-linear problems.\n3. **Recurrent (RNN) / Feedback:** Contains loops. Outputs feed back into previous layers. Acts as memory (Hopfield).\n4. **Self-Organizing / Competitive:** Neurons compete to win. Unsupervised (Kohonen SOM)." },
      { q: "Define linearly separable problems. Why logical XOR cannot be designed by single layer perceptron?", a: "**Exam Ready Answer:**\n**Linearly Separable:** A classification problem where a single straight line (hyperplane) can perfectly divide data points into distinct classes (e.g., AND, OR).\n**XOR Issue:** The XOR data points (0,1 and 1,0 vs 0,0 and 1,1) cross diagonally. It is mathematically impossible to draw a single straight line to separate them. A Multi-Layer Perceptron (MLP) is required." },
      { q: "Computational power in ANNs is determined by _______.", a: "**Answer:** The architecture, weights, and activation functions." },
      { q: "Ultimate results are produced in ANN at ________.", a: "**Answer:** The output layer." },
      { q: "The effect of the synaptic gap in a biological neuron is modelled in artificial neuron model as", a: "**Answer:** The connection weights." },
      { q: "Correlation between biological neuron & artificial neuron.", a: "**Answer:** Both have inputs (dendrites), a processing core (soma), and pass signals based on threshold." },
      { q: "Promise of an ANN is that it can explain the result - True/False?", a: "**Answer:** False! They are often considered 'black boxes'." },
      { q: "To generate the final output, the sum is passed on to a non-linear filter φ called _________.", a: "**Answer:** Activation Function." },
      { q: "What will be the minimum value of Bias (b), if Binary Step Function is used as activation function with threshold 2.3, and target is 1?", a: "**Answer:** The net input + bias must be $\\ge 2.3$." }
    ],
    quiz: [
      { type: "mcq", q: "Which activation function is defined as f(x) = 1 / (1 + e^-x)?", options: ["ReLU", "Tanh", "Sigmoid", "Step Function"], answer: 2, explanation: "This is the Sigmoid function." },
      { type: "mcq", q: "What component in an ANN is analogous to the biological Synapse?", options: ["Soma", "Weights", "Activation Function", "Axon"], answer: 1, explanation: "Synapses dictate the strength of a connection, just like Weights." },
      { type: "long", q: "Describe the concept of 'linear separability'. Why does the XOR gate fail this condition?" },
      { type: "mcq", q: "Which architecture allows signals to loop back, acting as a form of memory?", options: ["Single-layer Feedforward", "Multi-layer Feedforward", "Recurrent Neural Network (RNN)", "Kohonen SOM"], answer: 2, explanation: "RNNs (like Hopfield) have feedback loops." },
      { type: "long", q: "Explain the necessity of an activation function. What happens if a deep neural network only uses linear activation functions?" },
      { type: "mcq", q: "The bias 'b' in an artificial neuron is mathematically similar to:", options: ["The slope in a linear equation", "The y-intercept in a linear equation", "The derivative", "An exponential curve"], answer: 1, explanation: "Bias acts like the y-intercept, shifting the activation function left or right." },
      { type: "long", q: "Map the five main components of a biological neuron to their artificial McCulloch-Pitts counterparts." },
      { type: "mcq", q: "A single-layer perceptron can easily solve the logical AND problem.", options: ["True", "False"], answer: 0, explanation: "True. AND is a linearly separable problem." },
      { type: "long", q: "If you have a binary step function with a threshold of 0.5, and Net Input = 0.4, what will the output be?" },
      { type: "mcq", q: "Are ANNs generally good at explaining *how* they arrived at a specific result?", options: ["Yes, they are highly transparent", "No, they are often considered 'black boxes'"], answer: 1, explanation: "It is very difficult to trace the logic of millions of interconnected weights." },
      { type: "long", q: "Why is the Sigmoid activation function preferred over a hard Step Function for training networks with Gradient Descent?" },
      { type: "mcq", q: "Computational power in ANNs is primarily determined by:", options: ["Only the number of inputs", "Only the activation function", "The architecture, weights, and activation functions", "The clock speed of the CPU"], answer: 2, explanation: "The architecture, weights, and activation functions define the network's mapping capability." }
    ]
  },
  {
    id: "neural_learning",
    title: "6. ANN - Learning Math (Perceptron & Adaline)",
    easyConcept: "Learning means adjusting weights to reduce errors. The Perceptron uses the final 0/1 output to find the error. Adaline (Adaptive Linear Neuron) is smarter: it uses the raw math score (Net Input) *before* the 0/1 threshold to calculate the error, using the Delta Rule (LMS).",
    visualGuide: "Adaline Delta Rule Formula: W_new = W_old + α * (Target - Y_in) * X. This continuous error updating makes learning much smoother than a hard Perceptron step.",
    hasVisualizer: "none",
    examQuestions: [
      { q: "Mathematical Problem: Calculate the output of a McCulloch-Pitts Neuron.", a: "**Step-by-Step Math Guide:**\nAssume a neuron with 3 inputs: $X = [1, 0, 1]$. Weights $W = [0.5, -0.2, 0.8]$. Bias $b = -0.5$. Step Function threshold $\\theta = 0$.\n**1. Calculate Net Input ($Y_{in}$):**\n$Y_{in} = b + \\sum (X_i \\times W_i) = -0.5 + 0.5 + 0 + 0.8 = \\textbf{0.8}$\n**2. Apply Activation Function:**\nSince $Y_{in} \\ge 0$, Output $Y = \\textbf{1}$." },
      { q: "Explain the Adaline learning rule and Delta Rule mathematically. / How Adaline learning rule is different from Single Layer perceptron?", a: "**Exam Ready Answer:**\n**Adaline (Adaptive Linear Neuron)** uses the **Delta Rule (Least Mean Square - LMS)** to update weights. Unlike the Perceptron which uses the final thresholded output, Adaline uses the *linear net input* ($Y_{in}$) to calculate a continuous error.\n**Formula for Weight Update:**\n$W_{new} = W_{old} + \\alpha \\times (T - Y_{in}) \\times X$\nWhere $\\alpha$ = Learning rate, $T$ = Target, $Y_{in}$ = Net input, $X$ = Input vector. This allows efficient gradient descent." },
      { q: "State the difference between Adaline and Madaline networks.", a: "**Exam Ready Answer:**\n- **Adaline:** Consists of a single linear neuron using the Delta rule.\n- **Madaline (Many Adalines):** A multi-layer architecture consisting of a hidden layer of multiple Adalines connected to a single Madaline logic element (usually a fixed logic gate like AND/OR/Majority) in the output layer." },
      { q: "Design a Hebb net to implement logical AND function.", a: "**Exam Ready Answer:**\nHebbian Learning Rule: 'Cells that fire together, wire together'. Update rule: $\\Delta W = X_i \\times Y_{target}$.\nFor logical AND (Bipolar inputs -1 and 1):\nInit weights to 0. Apply input pairs (e.g., $X=[1,1], Y=1$). Update weights: $W_{new} = W_{old} + X \\times Y$. Repeat for all pairs in truth table." },
      { q: "Consider the following ANN with Sigmoidal Activation function, answer the following: (a) Total input (b) Final output (c) Error.", a: "**Answer:** Calculate Sum($w \\times x$), pass through $1/(1+e^{-x})$, then subtract from target to get error." },
      { q: "In simple perceptron learning rule change of synaptic weight is proportional to", a: "**Answer:** The learning rate, the input, and the error." },
      { q: "Error correction learning is like 'learning with teacher'. Is it true or false?", a: "**Answer:** True! It compares output to a target (teacher)." }
    ],
    quiz: [
      { type: "mcq", q: "If Net Input (Y_in) is 2.5 and Target is 1.0, what is the error used for weight update in Adaline?", options: ["1.5", "-1.5", "0.0", "3.5"], answer: 1, explanation: "Adaline error is (Target - Y_in). 1.0 - 2.5 = -1.5." },
      { type: "mcq", q: "The Hebbian learning rule is summarized by the phrase:", options: ["Survival of the fittest", "Cells that fire together, wire together", "Gradient descent", "Winner takes all"], answer: 1, explanation: "Hebbian learning strengthens synapses when both input and output are active." },
      { type: "long", q: "Explain mathematically why Adaline's error updating rule (Delta rule) is different and smoother than the standard Perceptron rule." },
      { type: "mcq", q: "What does MADALINE stand for?", options: ["Mathematical Adaline", "Many Adalines", "Matrix Adaline", "Max-Min Adaline"], answer: 1, explanation: "Madaline combines multiple Adaline units into a multi-layer network." },
      { type: "long", q: "Write down the mathematical formula for the Delta Rule (LMS) used in Adaline and define each variable." },
      { type: "mcq", q: "If an input vector is [1, 1], weights are [0.5, 0.5], and bias is -1, what is the Net Input (Y_in)?", options: ["1.0", "0.0", "-1.0", "0.5"], answer: 1, explanation: "(1*0.5) + (1*0.5) - 1 = 1 - 1 = 0.0" },
      { type: "long", q: "Describe the fundamental concept behind Error Correction Learning." },
      { type: "mcq", q: "In Hebbian learning, if Input X is 1 and Target Y is -1, the weight change (Delta W) will be:", options: ["1", "-1", "0", "0.5"], answer: 1, explanation: "Delta W = X * Y = 1 * -1 = -1." },
      { type: "long", q: "Calculate the net input for a McCulloch-Pitts neuron given inputs X=[0, 1, 1], weights W=[0.2, 0.4, 0.6] and Bias=0." },
      { type: "mcq", q: "The Perceptron updates its weights based on the error calculated:", options: ["Before the activation function", "After the activation function", "Randomly", "Using a genetic algorithm"], answer: 1, explanation: "The perceptron looks at the hard thresholded output to calculate error, unlike Adaline." },
      { type: "long", q: "Explain how you would design a Hebb net to implement a logical AND function using bipolar inputs." },
      { type: "mcq", q: "Change of synaptic weight in a simple perceptron learning rule is proportional to:", options: ["Learning rate only", "Learning rate, input, and error", "Input and bias", "Target and Output only"], answer: 1, explanation: "Delta W = alpha * (T - Y) * X." }
    ]
  },
  {
    id: "ann_advanced",
    title: "7. Advanced ANN: Backpropagation, Hopfield, SOM",
    easyConcept: "Backpropagation makes deep networks smart by passing error backwards to adjust hidden weights using Calculus. Hopfield networks are Recurrent (loops) and act as 'associative memory' (recognizing partial patterns). Kohonen SOM is Unsupervised; neurons 'compete' to cluster data without a teacher.",
    visualGuide: "Interactive Tool Below! Play with the Gradient Descent simulator. See how adjusting the Learning Rate changes how fast the error drops into the minimum valley.",
    hasVisualizer: "gradient",
    examQuestions: [
      { q: "What is meant by supervised, unsupervised and reinforcement learning?", a: "**Exam Ready Answer:**\n1. **Supervised Learning:** Network is provided with inputs paired with target outputs. It compares predictions to targets, calculates error, and adjusts weights. Example: Backpropagation.\n2. **Unsupervised Learning:** Network is provided with input data but NO targets. It discovers hidden structures or clusters on its own. Example: Kohonen SOM.\n3. **Reinforcement Learning:** Network interacts with an environment and receives rewards/punishments. Example: Game playing AI." },
      { q: "List the stages involved in training of Back Propagation network.", a: "**Exam Ready Answer:**\n**1. Initialization:** Set weights/biases to small random values.\n**2. Feedforward:** Inputs propagate through hidden layers to compute final output.\n**3. Error Calculation:** Compute error using a loss function $E = \\frac{1}{2} \\sum (T_k - Y_k)^2$.\n**4. Backpropagation:** Calculate error gradient at output, propagate backward to hidden layers using the Chain Rule of calculus.\n**5. Weight Update:** Adjust weights $\\Delta W = \\alpha \\times \\delta \\times Input$.\n**6. Iteration:** Repeat until error is minimized." },
      { q: "Explain the Hopfield Networks. What is associative memory?", a: "**Exam Ready Answer:**\n**Associative Memory:** Memory accessed by content. Given a partial/corrupted pattern, it retrieves the complete original pattern.\n**Hopfield Network:** An RNN acting as associative memory.\n- **Architecture:** Single-layer, fully interconnected (but not to itself $W_{ii}=0$).\n- **Weights:** Symmetric ($W_{ij} = W_{ji}$).\n- **Function:** Uses Hebbian learning to store patterns as 'local minima' in an Energy landscape. Given noisy input, it updates asynchronously to lower energy until settling in the closest memory valley." },
      { q: "Discuss the competitive, cooperative and adaptive process of Kohonen's SOM.", a: "**Exam Ready Answer:**\nKohonen Self-Organizing Map (SOM) is Unsupervised.\n1. **Competitive:** Neurons compute Euclidean distance to the input. The neuron with smallest distance wins (Winner-Takes-All).\n2. **Cooperative:** The winner identifies a spatial neighborhood around itself.\n3. **Adaptive:** The winner and its neighbors adjust weights to move closer to the input vector. Adjustment strength decreases with distance from the winner." },
      { q: "Which of the following ANN learning methods uses Euclidian distance between the weight vector and the input vector to compute the output ?", a: "**Answer:** Kohonen Self-Organizing Map (SOM)." },
      { q: "_____________ is a Systematic method for training multilayer artificial neural network.", a: "**Answer:** Backpropagation." },
      { q: "Write the applications of Back Propagation.", a: "**Answer:** Speech recognition, image classification, predicting stock prices." },
      { q: "BAM stands for ____________.", a: "**Answer:** Bidirectional Associative Memory." },
      { q: "In ________ mode of training, all neurons in Hopfield networks fire at random.", a: "**Answer:** Asynchronous." },
      { q: "How associated memory network is related to content addressable memories (CAM)? Draw architecture of auto-associative network. What is BAM?", a: "**Answer:** CAM retrieves data using part of the data itself. BAM maps forwards and backwards between two layers. Hopfield is a fully interconnected single layer auto-associative network." },
      { q: "To classify the output of logical XOR, what kind of ANN can we use?", a: "**Answer:** Multilayer Perceptron (MLP)." }
    ],
    quiz: [
      { type: "mcq", q: "Which mathematical concept allows Backpropagation to distribute the error backwards to hidden layers?", options: ["The Chain Rule of Calculus", "Lukasiewicz T-norm", "Euclidean Distance", "Simulated Annealing"], answer: 0, explanation: "The chain rule allows gradients to be computed layer by layer from output back to input." },
      { type: "mcq", q: "In a Kohonen SOM, the winning neuron is determined by:", options: ["Maximum activation", "Minimum Euclidean distance to input", "Maximum error", "Random selection"], answer: 1, explanation: "SOM uses competitive learning to find the weight vector mathematically closest to the input." },
      { type: "long", q: "Describe the Energy Function (Lyapunov Function) in Hopfield networks and explain how it acts as an associative memory." },
      { type: "mcq", q: "Which of the following is an example of Unsupervised Learning?", options: ["Backpropagation", "Kohonen SOM", "Adaline", "Madaline"], answer: 1, explanation: "Kohonen SOM clusters data without any target outputs provided." },
      { type: "long", q: "Outline the 6 main stages of training a Backpropagation neural network." },
      { type: "mcq", q: "What does BAM stand for in neural networks?", options: ["Binary Associative Memory", "Bidirectional Associative Memory", "Boolean Algorithmic Model", "Basic Activation Matrix"], answer: 1, explanation: "Bidirectional Associative Memory." },
      { type: "long", q: "Explain the difference between Supervised Learning and Reinforcement Learning." },
      { type: "mcq", q: "In a discrete Hopfield Network, the weight matrix diagonal (W_ii) is always:", options: ["1", "-1", "0", "Random"], answer: 2, explanation: "Neurons do not connect to themselves." },
      { type: "long", q: "What is the 'Cooperative Process' in a Kohonen SOM?" },
      { type: "mcq", q: "To solve the XOR problem, the neural network MUST have:", options: ["A linear activation function", "At least one hidden layer", "Symmetric weights", "A Kohonen map"], answer: 1, explanation: "XOR requires a Multi-Layer Perceptron (hidden layers) to draw multiple decision boundaries." },
      { type: "long", q: "Explain what Content Addressable Memory (CAM) is and how it relates to a Hopfield network." },
      { type: "mcq", q: "The mode of training where Hopfield neurons fire at random is called:", options: ["Synchronous", "Asynchronous", "Feedforward", "Backpropagated"], answer: 1, explanation: "In asynchronous mode, nodes are updated one at a time randomly." }
    ]
  },
  {
    id: "ga_math",
    title: "8. Genetic Algorithms (GA) & Selection Math",
    easyConcept: "Genetic Algorithms evolve solutions! Roulette Wheel Selection gives fitter individuals a mathematically bigger chance to reproduce. Crossover swaps their genes. Mutation flips a random bit to introduce new traits and prevent getting stuck.",
    visualGuide: "Interactive Tool Below! Input the fitness scores of 4 individuals. See how the Roulette Wheel calculates their exact selection probability percentages. Higher fitness = bigger slice!",
    hasVisualizer: "ga",
    examQuestions: [
      { q: "Mathematical Problem: Calculate Selection Probabilities for Roulette Wheel Selection.", a: "**Step-by-Step Math Guide:**\nPopulation fitness scores: $f_1 = 10, f_2 = 20, f_3 = 50, f_4 = 20$.\n**1. Calculate Total Fitness:** $\\sum f = 10 + 20 + 50 + 20 = \\textbf{100}$\n**2. Calculate Probability ($p_i$):** Formula: $p_i = f_i / \\sum f$\n- $p_1 = 10 / 100 = \\textbf{10\\%}$\n- $p_2 = 20 / 100 = \\textbf{20\\%}$\n- $p_3 = 50 / 100 = \\textbf{50\\%}$\n- $p_4 = 20 / 100 = \\textbf{20\\%}$" },
      { q: "Suppose chromosomes are binary strings of length 8. Perform single-point and two-point crossover.", a: "**Mathematical Example:**\nParent A = `11111111`, Parent B = `00000000`.\n**1. Single-Point Crossover:** Point after 3rd bit.\nSplit: `111 | 11111` and `000 | 00000`.\nOffspring: `11100000` and `00011111`.\n**2. Two-Point Crossover:** Points after 2nd and 6th bits.\nSplit: `11 | 1111 | 11` and `00 | 0000 | 00`.\nSwap middle: `11000011` and `00111100`." },
      { q: "Explain Elitism and why Mutation is strictly necessary.", a: "**Exam Ready Answer:**\n**Elitism:** Copying the absolute best individual(s) directly into the next generation without altering them. This guarantees maximum fitness never decreases.\n**Necessity of Mutation:** Crossover only mixes existing genes. If a critical bit is '0' in the entire population, crossover can NEVER produce a '1'. Mutation randomly flips bits (e.g., 1% probability), introducing entirely new genetic material to prevent stagnation in a **Local Optimum**." },
      { q: "State and discuss the Roulette wheel and tournament selection procedure.", a: "**Exam Ready Answer:**\n**Roulette Wheel:** Size of slice is proportional to fitness. Random spin selects individual. Weak individuals have a small chance to survive.\n**Tournament:** Randomly pick 'k' individuals from population. They compete, and the highest fitness wins. Fast, avoids scaling issues." },
      { q: "Which crossover technique can be used for Travelling Salesman Problem?", a: "**Exam Ready Answer:**\nStandard crossover fails in TSP because it creates invalid routes (visiting a city twice). TSP requires special operators like **Order Crossover (OX)**, **Partially Mapped Crossover (PMX)**, or **Cycle Crossover (CX)** to ensure all cities are visited exactly once." },
      { q: "What are some stopping conditions that a GA may implement?", a: "**Exam Ready Answer:**\n1. **Maximum Generations:** Halts after predefined iterations.\n2. **Fitness Threshold:** Target fitness is reached.\n3. **Convergence/Stagnation:** Highest fitness hasn't improved for X generations.\n4. **Time Limit:** Real-time processing limit reached." },
      { q: "The essential sites for recombination are known as ______.", a: "**Answer:** Crossover points." },
      { q: "Write some applications of Genetic Algorithm.", a: "**Answer:** Scheduling timetables, designing antennas, routing delivery trucks (TSP)." },
      { q: "Which process is carried out to separate chromosomal or genomic DNA?", a: "**Answer:** In GA, this refers to Crossover." },
      { q: "Explain GA based clustering algorithm.", a: "**Answer:** Using GA chromosomes to represent cluster centers and evolving them to minimize distances to data points." },
      { q: "In order to apply GA, an optimization problem should be formulated as", a: "**Answer:** A fitness/objective function to be maximized or minimized." },
      { q: "Which of the following properties is not guaranteed by a GA ?", a: "**Answer:** Finding the absolute perfect global optimum (it finds a very good one, but doesn't guarantee the absolute best)." },
      { q: "What happens in a GA, if (i) Crossover rate is increased, (ii) mutation rate is increased?", a: "**Answer:** High crossover explores faster. High mutation turns it into a purely random search, destroying good solutions." },
      { q: "If pc and pm be the crossover probability and the mutation probability of a GA then which of the following relations is true?", a: "**Answer:** $pc > pm$. Crossover is usually high (0.8), mutation is very low (0.01)." }
    ],
    quiz: [
      { type: "mcq", q: "If Total Fitness is 200, and Individual X has a fitness of 40, what is its Roulette selection probability?", options: ["40%", "20%", "200%", "4%"], answer: 1, explanation: "40 / 200 = 0.20, which is 20%." },
      { type: "mcq", q: "Which GA operator is primarily responsible for ensuring the search doesn't get permanently stuck in a local minimum?", options: ["Selection", "Crossover", "Mutation", "Elitism"], answer: 2, explanation: "Mutation introduces random, new genetic material, allowing the algorithm to 'jump' out of a local minimum trap." },
      { type: "long", q: "What is Elitism in Genetic Algorithms, and why is it important for the maximum fitness of a population?" },
      { type: "mcq", q: "Which crossover type swaps the segment strictly between two chosen indices?", options: ["Single-Point", "Uniform", "Two-Point", "Order Crossover"], answer: 2, explanation: "Two-point crossover divides the chromosome into three parts and swaps the middle section." },
      { type: "long", q: "Explain why standard single-point crossover cannot be used for the Travelling Salesman Problem (TSP)." },
      { type: "mcq", q: "If Elitism is NOT used, what might happen?", options: ["The algorithm will crash", "The best solution found so far might be lost in the next generation", "Mutation stops working", "The population size increases"], answer: 1, explanation: "Without elitism, probabilistic crossover/mutation might destroy the best chromosome." },
      { type: "long", q: "Explain why relying purely on Crossover without any Mutation would cause a Genetic Algorithm to fail." },
      { type: "mcq", q: "In order to apply a GA, the real-world problem must first be formulated as a:", options: ["Fuzzy Set", "Matrix", "Fitness/Objective Function", "Neural Network"], answer: 2, explanation: "The GA needs a fitness function to score and rank the chromosomes." },
      { type: "long", q: "Describe Tournament Selection and state one advantage it has over Roulette Wheel Selection." },
      { type: "mcq", q: "What generally happens if you set the Mutation rate extremely high (e.g., 80%)?", options: ["It converges faster", "It turns into a purely random search", "Elitism stops working", "The fitness function breaks"], answer: 1, explanation: "High mutation destroys good genetic building blocks faster than they can be saved, turning it into random guessing." },
      { type: "long", q: "List three common stopping conditions that can be implemented in a Genetic Algorithm flow." },
      { type: "mcq", q: "In typical GA parameters, how do crossover probability (pc) and mutation probability (pm) compare?", options: ["pm > pc", "pc > pm", "pc = pm", "pm = 1.0"], answer: 1, explanation: "Crossover is usually very high (~0.8) while mutation is kept very low (~0.01)." }
    ]
  },
  {
    id: "swarm_advanced",
    title: "9. Swarm Intelligence & Optimization Techniques",
    easyConcept: "Particle Swarm Optimization (PSO) mimics birds sharing locations to find food. Simulated Annealing (SA) slowly cools 'temperature' to settle into the perfect solution. Ant Colony Optimization (ACO) uses evaporating pheromone trails to find the shortest path.",
    visualGuide: "Interactive Tool Below! Adjust the Cognitive (c1) and Social (c2) parameters to see how the Particle's velocity vector is pulled towards its Personal Best and the Global Best.",
    hasVisualizer: "pso",
    examQuestions: [
      { q: "Explain the concept and mathematical update rules of Particle Swarm Optimization (PSO).", a: "**Exam Ready Answer:**\n**Concept:** PSO is a population-based metaheuristic inspired by bird flocking. A swarm of 'particles' (candidate solutions) flies through the search space. Each particle remembers its personal best position ($P_{best}$) and the swarm communicates the global best position ($G_{best}$).\n**Mathematical Update Rules:**\n1. **Velocity:** $V_{new} = w \\times V_{old} + c_1 \\times r_1 \\times (P_{best} - X_{old}) + c_2 \\times r_2 \\times (G_{best} - X_{old})$\n   (where $w$ is inertia, $c_1, c_2$ are cognitive/social constants, $r_1, r_2$ are random numbers).\n2. **Position:** $X_{new} = X_{old} + V_{new}$" },
      { q: "How does Simulated Annealing (SA) escape local optima?", a: "**Exam Ready Answer:**\nStandard algorithms (like Gradient Descent) only accept moves that improve the solution, causing them to get trapped in 'local minima'.\n**SA Mechanism:** SA accepts ALL improving moves. It also **probabilistically accepts WORSE moves**. \n- Probability: $P = e^{-\\frac{\\Delta E}{T}}$ (where $\\Delta E$ is how much worse the move is, $T$ is 'Temperature').\n- Initially, $T$ is high, meaning high probability of accepting worse moves (jumping out of traps). As $T$ 'cools down' towards 0, the algorithm settles into the Global Minimum." },
      { q: "Write short notes on Ant Colony Optimization (ACO) and Pheromone Evaporation.", a: "**Exam Ready Answer:**\n**ACO Concept:** Inspired by ants foraging. Ants wander randomly. Upon finding food, they return, laying a chemical trail (Pheromone).\n- **Positive Feedback:** Shorter paths accumulate pheromones faster. Subsequent ants choose paths probabilistically based on pheromone density, leading the colony to converge on the shortest path.\n- **Pheromone Evaporation:** Over time, pheromones evaporate. This allows 'bad' paths to be forgotten, encouraging exploration and preventing premature convergence on a local optimum." },
      { q: "What is Tabu Search?", a: "**Exam Ready Answer:**\n**Tabu Search:** Enhances local search algorithms by keeping a short-term memory called a **Tabu List**. Records recent moves and marks them as 'tabu' (forbidden). By forbidding the algorithm from returning to recently visited states, it prevents infinite loops and forces exploration of new regions, helping escape local optima." },
      { q: "What is Simulated Annealing?", a: "**Answer:** An optimization algorithm inspired by the slow cooling of metals to reach a low energy (optimal) state." },
      { q: "In Simulated Annealing (SA), the probability of accepting a solution worse than the current one...", a: "**Answer:** Decreases as the temperature decreases." },
      { q: "Tabu search is an example of", a: "**Answer:** A meta-heuristic optimization technique." },
      { q: "Simulated annealing is a soft computing technique to deal with...", a: "**Answer:** Optimization problems and avoiding local minima." },
      { q: "Parallel relaxation is a process related to the functionality of...", a: "**Answer:** Hopfield networks or Simulated Annealing." }
    ],
    quiz: [
      { type: "mcq", q: "In PSO, what does 'c2' (the social constant) pull the particle towards?", options: ["Its personal best position", "The swarm's global best position", "A random position", "The origin (0,0)"], answer: 1, explanation: "The social component pulls the particle towards the best position found by any member of the swarm (G_best)." },
      { type: "mcq", q: "Why is Pheromone Evaporation crucial in ACO?", options: ["To save computer memory", "To prevent premature convergence to a sub-optimal path", "To increase the ants' walking speed", "To make the math simpler"], answer: 1, explanation: "Evaporation ensures old, sub-optimal paths fade away, allowing the colony to continuously adapt and find the absolute shortest path." },
      { type: "long", q: "Explain the mechanism Simulated Annealing uses to escape local minima, referencing the concept of 'Temperature'." },
      { type: "mcq", q: "In Simulated Annealing, as the 'Temperature' parameter decreases towards zero, what happens to the probability of accepting a worse solution?", options: ["It increases to 100%", "It remains constant", "It decreases towards 0%", "It becomes negative"], answer: 2, explanation: "As it cools down, it stops jumping around and settles into the minimum, meaning probability of accepting a worse move drops to 0." },
      { type: "long", q: "In Particle Swarm Optimization, detail the three distinct mathematical components that influence a particle's new velocity calculation." },
      { type: "mcq", q: "Tabu Search uses a 'Tabu List' to:", options: ["Store the absolute best global solution", "Forbid the algorithm from revisiting recently evaluated solutions", "Calculate pheromone evaporation", "Increase the temperature"], answer: 1, explanation: "The Tabu list prevents infinite loops by banning recently visited states." },
      { type: "long", q: "Describe the 'Positive Feedback' loop mechanism in Ant Colony Optimization." },
      { type: "mcq", q: "Simulated Annealing is inspired by:", options: ["Bird flocking", "Ant foraging", "Cooling of metals in metallurgy", "Darwinian evolution"], answer: 2, explanation: "It mimics the physical annealing process of heating and slowly cooling a material." },
      { type: "long", q: "What role does the 'Inertia weight (w)' play in the Particle Swarm Optimization velocity update equation?" },
      { type: "mcq", q: "Which algorithm relies primarily on 'personal best' and 'global best' memories?", options: ["Genetic Algorithms", "Simulated Annealing", "Particle Swarm Optimization", "Ant Colony Optimization"], answer: 2, explanation: "PSO uses P_best and G_best to guide particles." },
      { type: "long", q: "Explain what a meta-heuristic optimization technique is, and name two examples from the syllabus." },
      { type: "mcq", q: "The probability function P = e^(-ΔE/T) is associated with which algorithm?", options: ["Particle Swarm Optimization", "Genetic Algorithms", "Simulated Annealing", "Tabu Search"], answer: 2, explanation: "This is the Boltzmann distribution used to calculate the probability of accepting a worse solution in SA." }
    ]
  }
];

window.tutorData = tutorData;